### ISSUE TITLE
Heads up and thanks and licensing question

### ISSUE THREAD

**Issue by gotjoshua** [ihaback/parcel-library-starter#54]
Just want to say thanks for a great base project to get me started on [this fork](https://github.com/onezoomin/parcel-edge-component)!

About the license:  
`"license": "ISC",`  

[It seems very liberal](https://en.wikipedia.org/wiki/ISC_license#License_terms), but i didn't grok if all derivative works need to carry the same license?
I ask because I'd like to create a template repo with a liberal license, and i don't want to step on any toes.
As your repo did not actually include a LICENSE file at the time of the fork,  
i think I'm legally in the clear to do what ever I want, but prefer to make respectful contact first.

**Comment by ihaback** [comment]
@gotjoshua You are free to use this code as you see fit 🙂
